ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd abbreviations) #completion
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_HISTORY_IGNORE='?(#c50,)'
ZSH_AUTOSUGGEST_COMPLETION_IGNORE='( |man )*'
